
CREATE OR REPLACE SYNONYM JEDNOSTKI_ORGANIZACYJNE FOR BD2A37.JEDNOSTKI_ORGANIZACYJNE ;

CREATE OR REPLACE SYNONYM PRACOWNICY FOR BD2A37.PRACOWNICY ;

CREATE OR REPLACE SYNONYM STANOWISKA FOR BD2A37.STANOWISKA ;

CREATE OR REPLACE SYNONYM STANOWISKA_PRACOWNIKOW FOR BD2A37.STANOWISKA_PRACOWNIKOW ;
